### User sign up POST request - endpoint 

POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Charlie",
    "company": "d sompany",
    "address": "Chor vilas,Lamba Ghar.",
    "phone": "8930240000",
    "email": "ghodas@flora.com",
    "password": "friendly_123"
}

###login authorization POST request

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "rasta3@lasta.com",
    "password": "friendly_123"
}

### GET request user profile - endpoint

GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhc3RhMkBsYXN0YS5jb20iLCJpYXQiOjE2MzUxMjUxNjksImV4cCI6MTYzNTEyNjA2OX0.4WyJLC7ASowVQv8_Fc_QKvRQRokH3XMxsrXel9712p0

### token routers
### authentication? GET refresh token request - once logged in, user can use refresh token for 30days

GET http://localhost:3001/v1/tokens/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhc3RhM0BsYXN0YS5jb20iLCJpYXQiOjE2MzU2NDA0NDUsImV4cCI6MTYzODIzMjQ0NX0.FhjYYCLAnUQQt9y90X34F-oBgiUrzAfSdurAJaMezE4

###reset password POST request API to receive reset password pin on email

POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "ghoda@flora.com"
}

###Update new password using pin sent to email - endpoint

PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "ghoda@flora.com",
    "pin":  "105971",
    "newPassword": "pass123"
}

### user logout endpoint 

DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhc3RhM0BsYXN0YS5jb20iLCJpYXQiOjE2MzUxMzA3ODEsImV4cCI6MTYzNTEzMTY4MX0.kbEJQ3Qv5cJ_ypnsNjRCcUqInTsFn-kwpUJxaM8IscY

### Ticket APIs

###Open new ticket

POST localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5cmFAZ21haWwuY29tIiwiaWF0IjoxNjM1MjI4NTQ2LCJleHAiOjE2MzUyMjk0NDZ9.1F09ZRgQKSN7VuEmpB73ESy-UqQORLdThBlH-ZkZkVU
Content-Type: application/json

{
    "subject": "343",
    "sender": "MREP MREP",
    "message": "Contact form not working, please fix"
}

###GET all tickets

GET localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5cmFAZ21haWwuY29tIiwiaWF0IjoxNjM1MjI4NTQ2LCJleHAiOjE2MzUyMjk0NDZ9.1F09ZRgQKSN7VuEmpB73ESy-UqQORLdThBlH-ZkZkVU

### GET single ticket

GET localhost:3001/v1/ticket/61774f47b1f25cbf4b733e6c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5cmFAZ21haWwuY29tIiwiaWF0IjoxNjM1MjE5Mjc1LCJleHAiOjE2MzUyMjAxNzV9.jkZELbRDwGcnBJADx1kniofZdFtIV0Cre3He6LCQMAs

### REPLY-UPDATE message to the ticket

PUT localhost:3001/v1/ticket/61779bba533ff2f30a8d156e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5cmFAZ21haWwuY29tIiwiaWF0IjoxNjM1MjE5Mjc1LCJleHAiOjE2MzUyMjAxNzV9.jkZELbRDwGcnBJADx1kniofZdFtIV0Cre3He6LCQMAs
Content-Type: application/json

{
    "subject": "3rd change testing confirmed changes",
    "sender": "MR4444P",
    "message": "Re-Confirming testing new message received to ticket"
}

### CLOSE the ticket

PATCH localhost:3001/v1/ticket/close-ticket/61776e7692ea535dec8de8b2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5cmFAZ21haWwuY29tIiwiaWF0IjoxNjM1MjE5Mjc1LCJleHAiOjE2MzUyMjAxNzV9.jkZELbRDwGcnBJADx1kniofZdFtIV0Cre3He6LCQMAs

###DELETE the ticket

DELETE localhost:3001/v1/ticket/61774efbb1f25cbf4b733e67
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhc3RhM0BsYXN0YS5jb20iLCJpYXQiOjE2MzUyMjA0NzcsImV4cCI6MTYzNTIyMTM3N30.qgToDeKhbXErfMXWhFjP91xzWC8s16cam594nOomXaU


### ADMIN AUTH routes

###create one admin minimum

POST http://localhost:3001/v1/admin/signup
Content-Type: application/json

{
    "name": "Admin man",
    "dob": "1992-11-26",
    "address": "Chor vilas,Lamba Ghar.",
    "phone": "8930240000",
    "email": "ghodas3@flora.com",
    "password": "friendly_123"
}

### login admin 

POST http://localhost:3001/v1/admin/login
Content-Type: application/json

{
    "email": "ghodas3@flora.com",
    "password": "friendly_123"
}

### GET request admin profile - endpoint

GET http://localhost:3001/v1/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdob2RhczNAZmxvcmEuY29tIiwiaWF0IjoxNjM1NjgyNTMxLCJleHAiOjE2MzU2ODM0MzF9.zKKS-xcjEaaDE3b5gfFIcu0U1tg7a4V1MCW5wWIZtFw

### admin logout endpoint 

DELETE http://localhost:3001/v1/admin/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdob2RhczNAZmxvcmEuY29tIiwiaWF0IjoxNjM1NjgyOTI1LCJleHAiOjE2MzU2ODM4MjV9.0n6kgTzphcVHAbbpIxnMuQXe0u8pLdXhy_EgsqynfWI

### ticket routes 

###get all tickets

GET http://localhost:3001/v1/admin/all-tickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdob2RhczNAZmxvcmEuY29tIiwiaWF0IjoxNjM1Njg3MzQwLCJleHAiOjE2MzU2ODgyNDB9.DW7RTdDgvlfXfCz2G6ru23rDDQvrT3YhSiDcdc-T6OY

###get tickets according to status

GET http://localhost:3001/v1/admin/find-tickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdob2RhczNAZmxvcmEuY29tIiwiaWF0IjoxNjM1Njg1NjM1LCJleHAiOjE2MzU2ODY1MzV9.vzY41lFZV9-fUpocJ1Lwg-jgFD-ryqUvFAQ8zbf-H8s
Content-Type: application/json

{
    "status": "pending operator response"
}
