### User sign up endpoint

POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Mrep Ayrahca",
    "company": "Random Daftar",
    "address": "Lamba Ghar, Chor vilas",
    "phone": "1010808030",
    "email": "ayra@gmail.com",
    "password": "secret123"
}

### user signin endpoint

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "ayra@gmail.com",
    "password": "secret123"
}

### GET a user profile endpoint

GET http://localhost:3001/v1/user
Authorization: 6gImF5cmFAZ21haWwuY29tIiwiaWF0IjoxNjM0OTQ1OTk4LCJleHAiOjE2MzQ5NDY4OTh9.AyVzzZ6s3KKk7QGIGVzoPPKa_4p1sn0ob_yNx79_LwE